# Configurações para testes locais
spring:
  config:
    activate:
      on-profile: local
  
  # Banco de Dados - Local (usando mesma config de dev)
  datasource:
    url: jdbc:oracle:thin:@10.10.0.14:1521:TASYHML
    username: pontetech
    password: Qvcp889z
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
  
  # JPA - Local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Configurações da API OdontoPrev - Local/Desenvolvimento
odontoprev:
  api:
    base-url: https://api-hml.odontoprev.com.br:8243
    base-url-auth: https://apim-hml.odontoprev.com.br
    base-url-login: https://api-hml.odontoprev.com.br:8243
    path: /dcms/empresa/2.0
    app-token: X2JlUWZkMW5PTnE5WWpyYVZwZkl5N2J0eVhJYTpCV25wMURLMlJkeXowYXNBVXU2QkFkSUdnM01h
    user:
      login: 13433638
      senha: gWZ84t1NCX3a
      appid: ODPV
  
  credentials:
    token: X2JlUWZkMW5PTnE5WWpyYVZwZkl5N2J0eVhJYTpCV25wMURLMlJkeXowYXNBVXU2QkFkSUdnM01h
    empresa: 787392
    usuario: 13433638
    senha: gWZ84t1NCX3a
    app-id: ODPV

# Logging para local
logging:
  level:
    com.odontoPrev: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    feign: DEBUG